image:
- Visual Studio 2019
- Visual Studio 2017
- Ubuntu
- macos

configuration:
- test

build: off

# Install Pester for testing, setup AWS Profiles and deploy minio via docker
install:
  - ps: $PSVersionTable
  - ps: Get-PSRepository -Name PSGallery
  - ps: Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
  - ps: Install-Module Pester -Scope CurrentUser -Force -SkipPublisherCheck -MinimumVersion 4.4.4 -MaximumVersion 4.999
  - ps: Import-Module -Name Pester -Force

  test_script:
  - ps: Invoke-Pester